; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[admin_menu][version] = "3.0-rc4"

projects[auto_entitylabel][version] = "1.1"

projects[ctools][version] = "1.3"

projects[bundle_inherit][version] = "1.0-alpha2"

projects[cer][version] = "2.x-dev"

projects[deploy][version] = "2.0-alpha1"

projects[entity][version] = "1.1+1-dev"
projects[entity][patch][] = "http://drupal.org/files/entity-entity_node_access-1780646-97.patch"

projects[entity_dependency][version] = "1.0-alpha1"

projects[entityreference][version] = "1.0"

projects[features][version] = "2.0-beta2"

projects[rules][version] = "2.3"

projects[uuid][version] = "1.0-alpha4"

projects[uuid_features][version] = "1.0-alpha3"

projects[views][version] = "3.7"

projects[views_rules][version] = "1.0"

