<?php
// $Id$

/**
 * @file
 * A module exemplifying Drupal coding practices and APIs.
 *
 * This module provides a block that lists all of the
 * installed modules. It illustrates coding standards,
 * practices, and API use for Drupal 7.
 */

/**
 * Implements hook_help().
 */
function openintegrity_helper_help($path, $arg) {
  if ($path == 'admin/help#openintegrity_helper') {
    return t('A helper module for Open Integrity Index.');
  }
}

function openintegrity_helper_form_evidence_node_form_alter(&$form, &$form_state, $form_id) {
  $form['field_evidence_date']['und']['#access'] = 0;
  $form['additional_settings']['#access'] = 0;
}

